# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net         

name: .NET

on:
  push:
    branches: [ "primary" ]
  pull_request:
    branches: [ "primary" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      # uses: actions/setup-dotnet@v4
      # with:
        # dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      # run: dotnet build --no-restore
    - name: Test
      # run: dotnet test --no-build --verbosity normal

    - name: Godot Mono Build
    # You may pin to the exact commit or the version.
    # uses: lillian1024/godot-mono-action@b0501ff96a5bf893cc2c56222b921ee796591c21
      uses: lillian1024/godot-mono-action@v1.0
    
      with:
      # Name of the exported binary
        name: VoxelFrontiers
      # Name of the preset in `export_presets.cfg` to use
        preset: Linux
      # Optional name of the subdirectory to put exported project in
        subdirectory: . # optional, default is 
      # Set true to output an artifact zip file
        package: true # optional
      # Location of Godot project in repository
        projectDir: . # optional, default is .
      # Whether or not to use `--export-debug`
        debugMode: false # optional
